<?php


namespace Drachenkatze\ZoneChecker\Checkers;


use PhpIP\IP;
use PhpIP\IPBlock;
use PhpIP\IPv4;
use PhpIP\IPv4Block;
use PhpIP\IPv6;

class CheckTarget extends AbstractChecker
{
    private $target = "";

    public static function canHandle(string $checkerType)
    {
        if ($checkerType == "check_target") {
            return true;
        }

        return false;
    }

    public function setConfig(array $config)
    {
        parent::setConfig($config); // TODO: Change the autogenerated stub

        if(array_key_exists("target",$config)) {
            $this->target = $config["target"];
        }
    }




    public function check()
    {
        if ($this->resourceRecord->getRdata()->toText() != $this->target) {
            $this->logError("Resource record does not point to {$this->target}");
        }
    }




}